# Generated by Django 3.1.7 on 2021-03-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitasApp', '0003_remove_receita_tempo_preparo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='tempo_preparo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
